[build]
  command = "echo 'No build needed for Python functions'"
  publish = "frontend"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"
  # Remove the DATABASE_URL from here - set it in Netlify dashboard instead

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"